---
spring:
  profiles: default

---
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./target/h2db/db:db1;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: test

spring.jpa:
  hibernate:
    ddl-auto: create-drop

---
spring:
  profiles: local

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://my-mysql:3306/soa_tickets
  username: root
  password:

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update
---
invoice:
  taxPercentage: 18
