version: '2'
services:
  my-traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=dck.mojserver.mk
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  my-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: soa_tickets
    volumes:
      - my-datavolume:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  soa-ticekts:
    image: akichukov/soa-tickets
    labels:
      - "traefik.port=8080"
      - "traefik.backend=soa-tickets"
      - "traefik.frontend.rule=Host:soa-tickets.arch-docker.com"
    links:
      - my-mysql
    depends_on:
      - my-mysql
      - my-traefik

volumes:
  my-datavolume: {}
